return {
	["project"] = "909Chan.github.io",
	["hermes"] = "froststarinteractive.github.io",
	["lynx"] = "lynx-luau.pages.dev",
	["playfab"] = "grilme99.github.io",
	["purse"] = "ryanlua.github.io",
	["react"] = "jsdotlua.github.io",
	["rocket"] = "teamfireworks.github.io",
	["satchel"] = "ryanlua.github.io",
	["sentry"] = "grilme99.github.io",
	["typeforge"] = "typeforge-luau.github.io",
	["ui-labs"] = "pepeeltoro41.github.io",
}
